### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by cornytrace**
This will enable opendf and bsatool to compile and run under MSVC and windows.
A few things to notice:
Visual Studio 2013 does not support defaulting move constructors, which mean the copy constructors cannot be deleted. Ugly but working fix is to put it all behind a #if statement.
Windows doesn't have a fnmatch function, so i took an implementation which was under GPL2+ and made it work.
Visual Studio doesn't like statements in the form of: (Struct){StructArgumentFoo, bar}. Instead it has to be Struct{StructArgumentFoo, bar}. I find this a bit weird but that's Visual Studio for you...
All required dll files (OSG, zlib, MyGUI, etc.) need to be manually copied to where the exe is or where the working directory is.

### CODE REVIEW

**Comment by kcat** [comment]
Unfortunately I'm getting a linker error:
`components/vfs/manager.cpp:150: undefined reference to `fnmatch(char const*, char const*, int)'`
It seems the non-Windows path is picking up the custom fnmatch.h instead of the system one. Perhaps it would be better to move the fnmatch.\* files to the misc/ folder, and include `misc/fnmatch.h` in Windows.

I'd also recommend putting

```
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
} // extern "C"
#endif
```

in fnmatch.h instead of enclosing the include statement.

**Comment by cornytrace** [comment]
Ok, Would you mind if i moved the misc folder into src? it would be neater to have all source files (execpt main.cpp) in src.

**Comment by kcat** [comment]
Hmm, well currently src is used for opendf itself, while things in misc and components are for shared code.

Perhaps we could rename src to opendf, move main.cpp into opendf (where it belongs), then put misc, components, tools, and opendf into src.

**Comment by cornytrace** [comment]
Sounds good. If you would be willing to do that, i can rebase this branch on it.

**Comment by kcat** [comment]
> Sounds good. If you would be willing to do that, i can rebase this branch on it.

Done. Hopefully Git will recognize the renames/moves and not have a problem with rebasing.

**Comment by cornytrace** [comment]
Ok, how about this?

**Comment by kcat** [comment]
Looks good.

**Pull request merged**
